builds:
  - main: cmd/exoip/main.go
    binary: exoip
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

sign:
  cmd: gpg
  args: ["--default-key", "B2DB6B250321137D9DB7210281426F034A3D05F7", "--detach-sign", "${artifact}"]
  artifacts: all

dockers:
  - image: exoscale/exoip
    dockerfile: Dockerfile.minimal
    binary: exoip
    skip_push: true
    tag_templates:
      - "{{ .Tag }}"
      - latest

nfpm:
  vendor: Exoscale
  homepage: https://www.exoscale.com
  maintainer: Exoscale Support <support@exoscale.com>
  description: Heartbeat monitor for Exoscale Elastic IP Addresses
  license: Apache 2.0
  formats:
    - deb
    - rpm

dist: build

git:
  short_hash: true

release:
  github:
    owner: exoscale
    name: exoip
  draft: true
