builds:
  - main: cmd/exoip/main.go
    binary: exoip
    goos:
      - linux
    goarch:
      - amd64

sign:
  cmd: gpg
  args: ["-a", "-u", "ops@exoscale.ch", "--detach-sign", "${artifact}"]
  artifacts: none

dockers:
  - image: exoscale/exoip
    dockerfile: Dockerfile.minimal
    binary: exoip
    skip_push: true
    tag_templates:
      - "{{ .Tag }}"
      - latest

dist: build

git:
  short_hash: true
