language: go

dist: trusty

go:
- 1.8
- 1.9
- tip

cache: apt

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - npm i -g codeclimate-test-reporter

install:
  - make deps

script:
  - make
  - go test -race -coverprofile=coverage.out -covermode=atomic .

after_success:
  - codeclimate-test-reporter < coverage.out
