language: go

dist: xenial
sudo: true

matrix:
  include:
  - go: "1.10.x"
    script:
      - go test -v ./...
      - goreleaser --snapshot --skip-sign
  - go: "1.11.x"
    script:
      - go test -v ./...
      - GO111MODULE=on go build -mod=vendor github.com/exoscale/exoip/cmd/exoip

cache: apt

addons:
  apt:
    packages:
      - rpm

env:
  - GORELEASER_VERSION=0.87.0 NFPM_VERSION=0.9.5

before_install:
  - wget https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_amd64.deb
  - sudo dpkg -i goreleaser_amd64.deb
  - wget https://github.com/goreleaser/nfpm/releases/download/v${NFPM_VERSION}/nfpm_amd64.deb
  - sudo dpkg -i nfpm_amd64.deb
