language: go

dist: trusty

go:
- 1.8
- 1.9
- tip

cache: apt

install:
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - test `gofmt -s -d . | tee -a /dev/fd/2 | wc -l` -eq 0
  - test `bin/golint . | tee -a /dev/fd/2 | wc -l` -eq 0
  - go tool vet .
  - make
  - # go test -v .
