language: go

dist: trusty

go:
- 1.8
- 1.9
- tip

env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=amd64

cache: apt

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - npm i -g codeclimate-test-reporter

install:
  - dep ensure

script:
  - make
  - go test -race -coverprofile=coverage.out -coveragemode=atomic .

after_success:
  - codeclimate-test-reporter < coverage.out
