language: go

dist: xenial
sudo: true

matrix:
  include:
  - go: "1.10.x"
    script:
      - go test -v ./...
      - goreleaser --snapshot --skip-sign
  - go: "1.11.x"
    script:
      - go test -v ./...
      - GO111MODULE=on go build -mod=vendor -o=exoip cmd/exoip/main.go

cache: apt

env:
  - GORELEASER_VERSION=0.85.1

before_install:
  - wget https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_amd64.deb
  - sudo dpkg -i goreleaser_amd64.deb
