language: go

dist: trusty

go:
- 1.8
- 1.9
- tip

cache: apt

install:
  - go get -u github.com/golang/lint/golint
  - git clone -b dev --single-branch https://github.com/exoscale/egoscale src/github.com/exoscale/egoscale
  - make deps

script:
  - make
  - test `gofmt -s -d . | tee -a /dev/fd/2 | wc -l` -eq 0
  - # test `bin/golint . | tee -a /dev/fd/2 | wc -l` -eq 0
  - go tool vet .
  - # go test -v .
