language: go

dist: xenial
sudo: true

go:
- 1.13.x

cache: apt

addons:
  apt:
    packages:
      - rpm

env:
  - GORELEASER_VERSION=0.128.0 NFPM_VERSION=1.2.0 GOLANGCI_LINT_VERSION=1.23.8 GO111MODULE=on

before_script:
  - curl -sL https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - >
    go test -mod vendor -race -coverprofile=c.out -covermode=atomic . ||
    go test -race -coverprofile=c.out -covermode=atomic .
  - >
    go build -mod=vendor github.com/exoscale/exoip/cmd/exoip ||
    go build github.com/exoscale/exoip/cmd/exoip

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

matrix:
  include:
  - name: goreleaser
    go: "1.13.x"
    script:
      - wget https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_amd64.deb
      - sudo dpkg -i goreleaser_amd64.deb
      - wget https://github.com/goreleaser/nfpm/releases/download/v${NFPM_VERSION}/nfpm_amd64.deb
      - sudo dpkg -i nfpm_amd64.deb
      - goreleaser --snapshot --skip-sign
  - name: lint
    go: "1.13.x"
    script:
      - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v${GOLANGCI_LINT_VERSION}
      - golangci-lint run ./...
