language: go

dist: trusty

go:
- "1.8"
- "1.9"
- "1.10"
- tip

cache: apt

services:
  - docker

before_install:
  - curl -sL https://git.io/goreleaser | head -n -2 | bash
  - tar -xf /tmp/goreleaser.tar.gz -C $GOPATH/bin/
  - npm i -g codeclimate-test-reporter

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v -vendor-only

script:
  - go test -race -coverprofile=coverage.out -covermode=atomic -v .
  - goreleaser --snapshot

after_success:
  - codeclimate-test-reporter < coverage.out
